PhysicalTherapyClinic/Controllers/ClientServiceController.cs
using Microsoft.AspNetCore.Mvc;
using PhysicalTherapyClinic.Models;
using PhysicalTherapyClinic.Services.Interfaces;

namespace PhysicalTherapyClinic.Controllers
{
    public class ClientServiceController : Controller
    {
        private readonly IDropDownListService _dropDownListService;
        private readonly IClientServicesService _clientServicesService;
        public ClientServiceController(IClientServicesService clientServicesService, IDropDownListService dropDownListService)
        {
            _dropDownListService = dropDownListService;
            _clientServicesService = clientServicesService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _clientServicesService.GetClientServices());
        }

        public IActionResult Add()
        {
            return View();
        }
        #region logic

        [HttpGet]
        public async Task<List<CompanyViewModel>> GetCompanies()
        {
            return await _dropDownListService.GetCompanies();
        }

        [HttpGet]
        public async Task<List<CompanyServiceViewModel>> GetCompanyServices(Guid companyId)
        {
            return await _dropDownListService.GetCompanyServices(companyId);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddClinetServiceViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _clientServicesService.AddClientService(model);

                return RedirectToAction(nameof(Index));

            }
            return View(model);
        }
        #endregion

    }
}

PhysicalTherapyClinic/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using PhysicalTherapyClinic.Models;
using PhysicalTherapyClinic.Services.Interfaces;

namespace PhysicalTherapyClinic.Controllers
{
    public class CompanyController : Controller
    {
        private readonly IDropDownListService _dropDownListService;
        public CompanyController(IDropDownListService dropDownListService)
        {
            _dropDownListService = dropDownListService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _dropDownListService.GetCompanies());
        }

        public async Task<List<CompanyViewModel>> GetCompanies()
        {
            return await _dropDownListService.GetCompanies();
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }  
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddCompanyViewModel addCompany)
        {
            await _dropDownListService.AddCompany(addCompany);
            return RedirectToAction("Index");
        }
    }
}

PhysicalTherapyClinic/Controllers/CompanyServiceController.cs
using Microsoft.AspNetCore.Mvc;
using PhysicalTherapyClinic.Models;
using PhysicalTherapyClinic.Services.Interfaces;

namespace PhysicalTherapyClinic.Controllers
{
    public class CompanyServiceController : Controller
    {
        private readonly IDropDownListService _dropDownListService;
        public CompanyServiceController(IDropDownListService dropDownListService)
        {
            _dropDownListService = dropDownListService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _dropDownListService.GetCompanyServices());
        }

        public async Task<IActionResult> Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddCompanyServiceViewModel addCompanyService)
        {
            await _dropDownListService.AddCompanyService(addCompanyService);
            return RedirectToAction("Index");
        }
    }
}

PhysicalTherapyClinic/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using PhysicalTherapyClinic.Models;
using PhysicalTherapyClinic.Services.Interfaces;

namespace PhysicalTherapyClinic.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IDropDownListService _dropDownListService;
        public ServiceController(IDropDownListService dropDownListService)
        {
            _dropDownListService = dropDownListService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _dropDownListService.GetServices());
        }

        public async Task<List<ServiceViewModel>> GetServices()
        {
            return await _dropDownListService.GetServices();
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddServiceViewModel addService)
        {
            await _dropDownListService.AddService(addService);
            return RedirectToAction("Index");
        }
    }
}

PhysicalTherapyClinic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhysicalTherapyClinic</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/Materia.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PhysicalTherapyClinic.styles.css" asp-append-version="true" />

</head>
<body>
    <header>


        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ClientService" asp-action="Index">الرئيسيه</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ClientService" asp-action="Index">خدمات العملاء</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Company" asp-action="Index">الشركات</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Service" asp-action="Index">الخدمات</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="CompanyService" asp-action="Index">خدمات الشركات</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>


    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PhysicalTherapyClinic - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>